import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import { calculateEstimate, ENGINE_VERSION } from './engine'
import { GOLDEN_CASES } from './goldens/fixtures'

/**
 * Golden files — `20-testing-strategy.md` §Unit and `08-pricing-engine.md` §Versioning.
 *
 * Two jobs, and the second is the interesting one:
 *
 *   **Regression.** Each committed expectation is recomputed and compared. A formula change
 *   shows up as a diff of real money in the PR rather than as a re-recorded snapshot.
 *
 *   **Version enforcement.** `08` calls a formula change without an `ENGINE_VERSION` bump a
 *   defect, *"because it silently invalidates comparisons across time"* — stored
 *   `PriceCalculation` rows carry the version, and two different formulas sharing a version
 *   makes historical figures unexplainable. So the checksum of every expectation is recorded
 *   here against the version that produced it. Regenerate the goldens without bumping and
 *   this test fails, naming both halves of the fix.
 *
 * Honest about its limit: nothing in a single file can stop someone editing a *past* version's
 * checksum along with the goldens. What it does guarantee is that the change cannot be
 * accidental — it takes a deliberate edit to a line that says, in words, not to.
 */

const GOLDEN_DIR = join(process.cwd(), 'src', 'modules', 'pricing', 'domain', 'goldens')

/**
 * Append-only. One entry per `ENGINE_VERSION` that has ever produced goldens.
 *
 * **Do not edit an existing line.** To change the formula: bump `ENGINE_VERSION`, run
 * `pnpm goldens:pricing`, and add a *new* entry with the checksum the failure prints.
 */
const GOLDEN_CHECKSUMS: Readonly<Record<number, string>> = {
  1: '3cfc15779432caf04f0eca48973ae53b50ad670c9f6c9ebec45337d63e48d23b',
}

type Golden = {
  name: string
  covers: string
  engineVersion: number
  input: (typeof GOLDEN_CASES)[number] extends never ? never : Record<string, unknown>
  expected: ReturnType<typeof calculateEstimate>
}

function readGolden(name: string): Golden {
  return JSON.parse(readFileSync(join(GOLDEN_DIR, `${name}.json`), 'utf8')) as Golden
}

function checksum(): string {
  const hash = createHash('sha256')
  // Sorted by name so the digest does not depend on directory order.
  for (const testCase of [...GOLDEN_CASES].sort((a, b) => a.name.localeCompare(b.name))) {
    hash.update(testCase.name)
    hash.update(JSON.stringify(readGolden(testCase.name).expected))
  }
  return hash.digest('hex')
}

describe('golden files', () => {
  it.each(GOLDEN_CASES.map((testCase) => [testCase.name, testCase] as const))(
    '%s reproduces its committed expectation',
    (_name, testCase) => {
      const golden = readGolden(testCase.name)
      const actual = calculateEstimate(testCase.project, testCase.priceBook, testCase.settings)

      expect(actual).toEqual(golden.expected)
    },
  )

  it('covers every documented outcome, not only the happy one', () => {
    const statuses = new Set(
      GOLDEN_CASES.map(
        (testCase) =>
          calculateEstimate(testCase.project, testCase.priceBook, testCase.settings).status,
      ),
    )

    // `08` §Failure modes has three outcomes and all three are worth pinning: a golden set
    // that only covers priced projects proves nothing about the two that customers hit.
    expect([...statuses].sort()).toEqual(['price-on-request', 'priced', 'unpriceable'])
  })

  it('was generated by the current engine version', () => {
    for (const testCase of GOLDEN_CASES) {
      expect(readGolden(testCase.name).engineVersion, testCase.name).toBe(ENGINE_VERSION)
    }
  })

  it('has a recorded checksum for this engine version', () => {
    const recorded = GOLDEN_CHECKSUMS[ENGINE_VERSION]

    expect(
      recorded,
      `ENGINE_VERSION ${ENGINE_VERSION} has no entry in GOLDEN_CHECKSUMS. Add one with the ` +
        `checksum below — do not edit an existing entry:\n  ${checksum()}`,
    ).toBeDefined()

    expect(
      checksum(),
      `The golden expectations changed under ENGINE_VERSION ${ENGINE_VERSION}.\n` +
        `08 §Versioning: a formula change without a version bump is a defect, because stored\n` +
        `PriceCalculation rows carry the version and comparisons across time stop meaning\n` +
        `anything. Bump ENGINE_VERSION, re-run 'pnpm goldens:pricing', and ADD a new entry to\n` +
        `GOLDEN_CHECKSUMS. If the change was not intended, revert the goldens instead.`,
    ).toBe(recorded)
  })

  it('never records a fractional kuruş anywhere in a breakdown', () => {
    for (const testCase of GOLDEN_CASES) {
      const golden = readGolden(testCase.name)
      if (golden.expected.status !== 'priced') continue

      for (const [key, value] of Object.entries(golden.expected.breakdown)) {
        if (typeof value === 'number' && key.endsWith('Kurus')) {
          expect(Number.isInteger(value), `${testCase.name}.${key}`).toBe(true)
        }
      }
    }
  })
})
